### ISSUE TITLE
Root element width is being miscalculated.

### ISSUE THREAD

**Issue by jpamarohorta** [skoob13/react-masonry-infinite#3]
Although the parent element of the root element occupies 100% width of the page (1440px), the root element width is being style with 4354px, which makes the layout break (all the positions are wrong).

Any idea why is this happening? I'm using a simple code like the example one.

**Comment by hew** [comment]
Looks like the culprit is Bricks. When I target the same div directly with Bricks, I get the same miscalculation. Might be related to https://github.com/callmecavs/bricks.js/pull/35

**Comment by hew** [comment]
Actually, @jpamarohorta there is a chance that you simply need to set the **same width** on all the cild elements. Mine were variable and it actually caused that parent width issue. 

Bricks, fundamentally, is a variable **height** library. Variable width completely throws it off.

**Comment by skoob13** [comment]
Was fixed in [1.8.0](https://github.com/callmecavs/bricks.js/releases/tag/v1.8.0) Bricks.js update.

**Comment by irealva** [comment]
I'm still getting this same problem actually... after a lot of trial and error, even with the Brick.js update the solution is to give the child elements a fixed width. If you don't add a width, the root element's width is off by a lot.
